pagopa/io-pagopa-proxy

package.json, tslint.json, yarn.lock
Also adds new rule "no-tslint-disable-all" that warns when all tslint rules gets disabled.
=> Imports custom tslint rules

README.md
Add additional information to README to start server
=> [#159228861] Add additional istruction to start server on README

package.json
Fix prettify command into package.json
=> [#159297002] Fix prettify command into package.json

src/Configuration.ts
Update Redis default port as described on README and as described by REDIS as default installation
=> [#159300269] Update Redis port as project README and REDIS default config

Dockerfile
Add yaml generator to Dockerfile
=> Add pagopa_api folder to dockerFile

README.md, src/App.ts, src/Configuration.ts, src/services/pagopa_api/PPTPortClient.ts, src/utils/SoapUtils.ts
WIP: I'm testing it sniffing packets on my local env.
=> [#159626572] Support HOST option for HTTP HEADER to PagoPa

README.md, src/Configuration.ts, src/services/PaymentsService.ts
- Read PAGOPA_WS_URI parameter (URI related to PagoPA SOAP WS) from Environment variables
- Change PAGOPA_WS_URI default value
- Add log when PagoPA communication catch an error
=> Change PAGOPA SOAP URI + Add log catching errors

api_pagopa.yaml, src/controllers/restful/PaymentController.ts
Change error retrieved in case of PagoPa application errors.
This PR will change the actual 403 code to 500.
WIP Information:
- Waiting to check\solve a backend problem related to HTTP messages with code 500
Update: WIP point solved with last PR on italia-backend:
https://github.com/teamdigitale/italia-backend/pull/277/files
=> [#159587517] Change error 403 to 500 for PagoPa application errors

src/utils/PaymentsConverter.ts
Change qrcode elements order into SOAP sequence
=> change_qrcode_elements_order

api_pagopa.yaml
Fix optional fields for entebeneficiario exposed to backend
=> Fix optional fields for entebeneficiario

src/utils/PaymentsConverter.ts, src/utils/__tests__/PaymentConverter.test.ts, src/wsdl/NodoPerPsp.wsdl
Retrieve causaleVersamento from spezzoni provided by PagoPA
=> Fix_spezzoni_handling

src/services/PaymentsService.ts
Log response and body on parse error, see https://github.com/vpulim/node-soap/blob/fa96454e22bbb9eadc0f9fdcf6e62c980b2eca05/lib/client.js#L405
=> Log response on exception

src/utils/PaymentsConverter.ts, src/utils/__tests__/PaymentConverter.test.ts
The purpose of this PR is to add check for optional field of [nodoTipoDatiPagamentoPA](https://github.com/pagopa/pagopa-api/blob/3bf6d11c079aea13fe99e1f46061904dc5f9c7e8/nodo/NodoPerPsp.wsdl#L139)
- updated `getPaymentRequestsGetResponse `
- added `NodoVerificaRPTOutput NotFullFilled` test
=> [PAG-752] add check optional field of enteBeneficiario

src/controllers/restful/PaymentController.ts, src/services/Nm3Service.ts, src/services/pagopa_api/NodoNM3PortClient.ts, src/utils/PaymentsConverter.ts, src/utils/SoapUtils.ts, src/utils/__tests__/MockedData.ts, src/utils/__tests__/PaymentConverter.test.ts, src/wsdl/nodeForIO.xsd, yarn.lock
- fix input amount as `ImportoEuroCents` for NM3 activation;
- add test for node input request for NM3 activation;
- delete iban in api response for NM3 activation;
- add post processing xml request to add 2 decimal
The goal of this PR is to fix payment activations for NM3 payment.
run unit test
=> [PAG-607] some fix

src/controllers/restful/PaymentController.ts, src/services/Nm3Service.ts, src/utils/AIUtils.ts, src/utils/__tests__/MockedData.ts
- add feature flag `NM3_ENABLED`;
- rewrite:
-  `PPT_PAGAMENTO_IN_CORSO` --> `PAA_PAGAMENTO_IN_CORSO`
-  `PPT_PAGAMENTO_DUPLICATO` --> `PAA_PAGAMENTO_DUPLICATO`
when `NM3_ENABLED`  is equal to false;
- return `PPT_AUTORIZZAZIONE` in verify step when `NM3_ENABLED` is equal to false and node return data for payment notice;
The goal of this PR is to add a new feature flag in order to disable payments NM3 according to [this solution](https://pagopa.atlassian.net/wiki/spaces/PAG/pages/389288324/Classificazione+FaultCode+per+IO#Workaround-temporaneo).
Run app locally with nodo-mock (see readme);
=> [PPR-162] nm3 feature flag

src/controllers/restful/PaymentController.ts
-fix check  error code PPT_PAGAMENTO_IN_CORSO and PPT_PAGAMENTO_DUPLICATO
=> [PPR-162] fix rempping

src/utils/PaymentsConverter.ts
- fix denominazioneBeneficiario in activate nm3 response
The goal of this PR is to fix denominazioneBeneficiario, setting with `activateIOPaymentRes.companyName`
=> Hotfix denominazioneBeneficiario in activate nm3

.env.example, api-tests/k6-payments-activation.js
- update .env to use in local env
- add k6 tests in order to tests payment activations in local env
The goal of this PR is to update the configuration to start the `pagopa-proxy` locally with the [node-mock](https://github.com/pagopa/io-pagopa-node-mock).
- `docker-compose up`
- `k6 run k6-payment-activations.js`
=> [IOPAY-420] updata local config

src/utils/PaymentsConverter.ts
- disable `codiceUnitOperBeneficiario` for NM3 payments.
=> disable codiceUnitOperBeneficiario for nm3

.devops/pagopa-code-review-pipelines.yml, .devops/pagopa-deploy-pipelines.yml, .gitignore, api-tests/k6-payments-activation.js, package.json, src/Configuration.ts, src/__integration__/PaymentController.test.ts, src/controllers/restful/PaymentController.ts, src/services/Nm3Service.ts, src/utils/PaymentsConverter.ts, src/utils/__tests__/MockedData.ts, src/utils/__tests__/PaymentConverter.test.ts, yarn.lock
=> [IOPAY-431] fix configuration

api-spec/api-for-io.yaml
- add api specs dedicated to io-backend
=> [IOPAY-485] add api spec dedicated to io

api-spec/api-for-checkout.yaml
- update  api spec for checkout
=> UPDATE api spec for checkout

api-spec/api-for-checkout.yaml, api-spec/api-for-io.yaml, api-spec/api-pagopa-proxy.yaml, package.json, src/App.ts, src/Configuration.ts, src/__integration__/PaymentController.test.ts, src/__integration__/fake/fakePagamentiTelematiciPspNodoAsyncClient.ts, src/__integration__/fake/fakePagamentiTelematiciPspNodoNm3AsyncClient.ts, src/controllers/restful/PaymentController.ts, src/services/Nm3Service.ts, src/services/PaymentsService.ts, src/services/pagopa_api/NodoNM3PortClient.ts, src/services/pagopa_api/PPTPortClient.ts, src/utils/SoapUtils.ts, src/utils/__tests__/MockedData.ts, src/utils/types.ts, yarn.lock
* Fix timeout usages
Local testing with nodo-mock
=> Fix timeouts in SOAP clients

.devops/pagopa-code-review-pipelines.yml, jest.integration.js, package.json, src/__integration__/PaymentController.test.ts, src/__integration__/fake/fakePagamentiTelematiciPspNodoAsyncClient.ts, src/__integration__/fake/fakePagamentiTelematiciPspNodoNm3AsyncClient.ts, src/utils/PaymentsConverter.ts, src/utils/__tests__/PaymentConverter.test.ts
- Add test for Nm3 payments
- publish code coverage in azure devops
The goal of this PR is to add some tests for Nm3 payments and publish code coverage (cobertura report) on Azure Devops, in order to have coverage report related to pipeline run.
- yarn test:coverage
- yarn test:integration
=> Review tests

api-tests/checkout-payments.tests.json
=> add recaptchaResponse in api tests

src/Configuration.ts, src/__integration__/PaymentController.test.ts, src/controllers/restful/PaymentController.ts, src/services/Nm3Service.ts
- Update clientId check to enable PN as a client using the Checkout configuration set
- linting, unit, integration (`yarn lint && yarn test`)
=> [CHK-318] Add PiattaformaNotifiche client support

api-spec/api-pagopa-proxy.yaml, src/utils/responses.ts, src/utils/types.ts
=> [CHK-464] Add missing error code

src/utils/PaymentsConverter.ts
=> Fix description in VerifyPayment

src/utils/PaymentsConverter.ts, src/utils/__tests__/MockedData.ts, src/utils/__tests__/PaymentConverter.test.ts
- add substring(0,70) for companyName
The goal of this PR is to truncate the companyName (denominazioneEnte) with a length greater than 70 characters until you complete the check with the checkout and App IO.
=> [CHK-477] denominazione with more than 70 chars

api-tests/checkout-payments.auth.v1.tests.json, api-tests/checkout-payments.auth.v2.tests.json, api-tests/checkout-payments.tests.json
- add `dueDate` check in `api-tests` for all versions exposed by `pagopa-proxy`;
=> CHK-575: Add dueDate in api test

src/utils/PaymentsConverter.ts, src/utils/__tests__/MockedData.ts, src/utils/__tests__/PaymentConverter.test.ts, yarn.lock
=> [CHK-770] error in verifica prod - denomUnitOperBeneficiario set to 70 chars

.github/create_dashboard.yaml
added a new github action to create dashboard
=> github action

.github/workflows/create_dashboard.yaml, api-spec/api-for-io.yaml
=> Test2 opex

.github/workflows/create_dashboard.yaml, api-spec/api-for-io.yaml
=> Test3 opex

.github/workflows/create_dashboard.yaml, monitor/config-dev.yaml, monitor/config-prod.yaml, monitor/config-uat.yaml
=> refactor(monitoring): change default spec for auto dashboard generation

.opex/api-for-checkout/env/prod/config.yaml, .opex/api-for-io/env/prod/config.yaml
* make response time thresholds more lax
=> refactor(opex): make response time thresholds more lax

.opex/api-for-checkout/env/prod/config.yaml, .opex/api-for-io/env/prod/config.yaml, .opex/api-pagopa-proxy/env/prod/config.yaml
=> fix(opex): make default timespan for availability events 10m

.opex/api-for-checkout/env/prod/config.yaml, .opex/api-for-io/env/prod/config.yaml
* set availability threshold to 50%
=> refactor(opex): set availability alert threshold to 50%
